### ConfigMap, Deployment, HPA, Secret, Service, Service Account
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-app
data:
  DB_NAME: angel
  MYSQL_SERVER_NAME: mysql.default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: counter-app
  name: counter-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: counter-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: counter-app
        app.kubernetes.io/name: counter-app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: counter-app
        - configMapRef:
            name: counter-app
        image: account_id.dkr.ecr.ap-southeast-1.amazonaws.com/counter-app:$IMAGE_TAG
        imagePullPolicy: IfNotPresent
        name: counter-app
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1500m
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
      serviceAccount: counter-app
      serviceAccountName: counter-app
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: counter-app
  name: counter-app
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-app
--- 
apiVersion: v1
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: counter-app
type: Opaque
--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: counter-app
  labels:
    app.kubernetes.io/name: counter-app
  name: counter-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: counter-app
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: counter-app
  labels:
    app.kubernetes.io/name: counter-app